library('ggplot2')
library('ggpubr')
library('utils')
library('dplyr')
library(cowplot)

# Upload mock data
mock<- read.csv("./Mock_community_data/Mock_all_primers.csv",h=T)
# Calculte seq length for each primers
mock_read_length <- mock %>%
  group_by(Seq_length, Primer) %>%
  summarize(count = n())%>%
  mutate(Seq_length=as.character(Seq_length)) 
# Plot fig S1A
ggplot(mock_read_length, aes(y=count, x=Seq_length, fill=Primer))+
  geom_bar(stat="identity")+
  scale_fill_manual(values = Primer_color)+
  scale_y_continuous(breaks = seq(0,10, by = 2)) +
  theme_pubr() +
  theme(text = element_text(size = 10),
        legend.key.size = unit(3, 'mm'),
        axis.title = element_text(face = "bold", size = 10),
        legend.title = element_text(face = "bold", size = 10),
        axis.text.x = element_text(angle = 45,hjust = 1),
        legend.position = "right",
        strip.text = element_blank()) +
  guides(fill = guide_legend("Primers", ncol = 1))+
  xlab("ASV sequence length") + ylab("Number of ASVs") 
# Save to pdf
ggsave("./fig_S1.pdf",
       units = "mm", 
       width = 90, 
       height = 60,
       dpi=300)
# Upload error data       
mock_error<-read.csv("./Mock_community_data/zymo_vs_primers.csv",h=T)

# Create bar plot
bar_plot <- ggplot(mock_error, aes(y=ASVs, x=Genus, fill=Primers)) +
  geom_bar(position = "dodge", stat="identity") +
  scale_fill_manual(values = Primer_color) +
  scale_y_continuous(breaks = seq(0, 5, by = 1), name = "Number of ASVs") +
  theme_pubr() +
  theme(text = element_text(size = 10),
        legend.key.size = unit(3, 'mm'),
        axis.title = element_text(face = "bold", size = 10),
        legend.title = element_text(face = "bold", size = 10),
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "right",
        strip.text = element_blank()) +
  guides(fill = guide_legend("Primers", ncol = 1)) +
  xlab("Genus")

# Create error point plot
error_plot <- ggplot(mock_error, aes(y=Error, x=Genus, color=Primers)) +
  geom_point(position = position_dodge(width = 0.6)) +
  scale_color_manual(values = Primer_color) +
  scale_y_continuous(breaks = seq(0, 12, by = 2), name = "Number of errors") +
  theme_pubr() +
  theme(text = element_text(size = 10),
        legend.key.size = unit(3, 'mm'),
        axis.title.y = element_text(face = "bold", size = 10),
        axis.title.x = element_blank(),
        legend.title = element_text(face = "bold", size = 10),
        axis.text.x = element_blank(),
        legend.position = "right",
        strip.text = element_blank()) +
  guides(color = guide_legend("Primers", ncol = 1)) +
  xlab("Genus")

# arrange the plots
plot_grid(error_plot,bar_plot, ncol = 1, align = "v")

ggsave("./fig_S1B.pdf",
       units = "mm", 
       width = 90, 
       height = 140,
       dpi=300)
